### ISSUE TITLE
Nationality

### ISSUE THREAD

**Issue by sezbee** [wentjun/covid-19-sg#6]
Hi,

Thanks for building this dataset, I am using it in my ConV in SG Tableau dashboard https://public.tableau.com/profile/sarah.burnett#!/vizhome/ConVinSG/ConV?publish=yes , prior to this I was manually pulling the data from the MOH website, although I am still for the top half of the dashboard. The nationality seems to include cases related to and pass details, for now I have build a clean up using Tableau Prep.

**Comment by wentjun** [comment]
@sezbee awesome dashboard! Thanks for doing this. Do let me know if there are any additional data that you might need.

Just a quick brief over how the data is scraped. I usually update the data at least twice a day.

Usually, the daily detailed case files are released between 8pm-11pm. That is when I run my script which parses the cases from the PDF files. Unfortunately, the script is still a WIP, thats why the data will be inaccurate, especially for the nationality field. 

The second batch of updates come at around noon (the following day), whereby I will run another script to scrape the MOH dashboard (https://experience.arcgis.com/experience/7e30edc490a5441a874f9efe67bd8b89). Data from this batch will be much more accurate since I am getting values from the DOM itself.

**Comment by wentjun** [comment]
@sezbee I have noticed that the nationality fields are missing for some of the cases. I have actually cleaned up the data yesterday. Perhaps you might want to update them?

**Comment by sezbee** [comment]
I have updated my Tableau Prep Flow (to clean the data) and my Tableau Viz, thanks for this and thanks for adding in gender, I have also added that back in.

https://public.tableau.com/profile/sarah.burnett#!/vizhome/ConVinSG/ConV?publish=yes
